config/routes.rb
Rails.application.routes.draw do
  resources :shots
  
  devise_for :users, controllers: { registrations: 'registrations' }
  
  root 'shots#index' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shot.rb
class Shot < ApplicationRecord

   belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :shots, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end 

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: [:show, :edit, :update, :destroy]

  # GET /shots
  # GET /shots.json
  def index
    @shots = Shot.all
  end

  # GET /shots/1
  # GET /shots/1.json
  def show
  end

  # GET /shots/new
  def new
    @shot = Shot.new
  end

  # GET /shots/1/edit
  def edit
  end

  # POST /shots
  # POST /shots.json
  def create
    @shot = Shot.new(shot_params)

    respond_to do |format|
      if @shot.save
        format.html { redirect_to @shot, notice: 'Shot was successfully created.' }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shots/1
  # PATCH/PUT /shots/1.json
  def update
    respond_to do |format|
      if @shot.update(shot_params)
        format.html { redirect_to @shot, notice: 'Shot was successfully updated.' }
        format.json { render :show, status: :ok, location: @shot }
      else
        format.html { render :edit }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1
  # DELETE /shots/1.json
  def destroy
    @shot.destroy
    respond_to do |format|
      format.html { redirect_to shots_url, notice: 'Shot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shot_params
      params.require(:shot).permit(:title, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Dribble</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width-device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if flash[:notice] %>
  <div class="notification is-primary global-notification">
    <p class="notice"><%= notice %></p>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
  <% end %>

  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5 has-text-white">Dribbble Clone</h1>
      <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id="navbar" class="navbar-menu">

      <div class="navbar-start">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'Shots', root_path , class:"button is-dark" %>
            </p>
          </div>
        </div>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <% if user_signed_in? %>
            <p class="control">
              <%= link_to new_shot_path, class:"button is-primary"  do %>
              <span class="icon is-small"><i class="fa fa-upload"></i></span>
              <span>New Shot</span>
              <% end %>
            </p>
            <p class="control">
              <%= link_to current_user.name, edit_user_registration_path, class:"button is-dark" %>
            </p>
            <p class="control">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"button is-dark" %>
            </p>
            <% else %>
            <p class="control">
              <%= link_to "Sign In", new_user_session_path, class:"button is-dark" %>
            </p>
            <p class="control">
              <%= link_to "Sign up", new_user_registration_path, class:"button is-dark"%>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <%= yield %>
</body>

</html>

app/views/shots/_form.html.erb
<%= simple_form_for(@shot) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <%= f.input :title %>
  <%= f.input :description %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/shots/edit.html.erb
<h1>Editing Shot</h1>

<%= render 'form', shot: @shot %>

<%= link_to 'Show', @shot %> |
<%= link_to 'Back', shots_path %>

app/views/shots/index.html.erb
<h1>Shots</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shots.each do |shot| %>
    <tr>
      <td><%= shot.title %></td>
      <td><%= shot.description %></td>
      <td><%= shot.user_id %></td>
      <td><%= link_to 'Show', shot %></td>
      <td><%= link_to 'Edit', edit_shot_path(shot) %></td>
      <td><%= link_to 'Destroy', shot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shots/new.html.erb
<h1>New Shot</h1>

<%= render 'form', shot: @shot %>

<%= link_to 'Back', shots_path %>

app/views/shots/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @shot.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shot.description %>
</p>

<%= link_to 'Edit', edit_shot_path(@shot) %> |
<%= link_to 'Back', shots_path %>